
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'contatos-api'
    static_configs:
      - targets: ['contatos-api:8080']

  - job_name: 'auth-api'
    static_configs:
      - targets: ['auth-api:8080']

  - job_name: 'areas-api'
    static_configs:
      - targets: ['areas-api:8080']

  - job_name: 'consulta-contatos-function'
    static_configs:
      - targets: ['consulta-contatos-function:8080']
