global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'contatos-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'host.docker.internal:8083'
    scheme: 'http'

  - job_name: 'areas-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'host.docker.internal:8081'
    scheme: 'http'

  - job_name: 'auth-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'host.docker.internal:8082'
    scheme: 'http'