global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'aspnet-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'host.docker.internal:8080'
    scheme: 'http'